[package]
name = "minurl"
version = "0.2.0+git"
edition = "2024"
authors = ["Elias Rohrer <dev@tnull.de>"]
license = "MIT OR Apache-2.0"
description = "A minimal library for parsing and validating URLs."

[dependencies]

[dev-dependencies]
proptest = "1.5"
url = "2"
